---
roles:
  # Roles from my DevHub (prepended with "devhub." to indicate this is a role from somewhere else (my DevHub), not specific to this project)
  - name: devhub.users 
    src: https://github.com/CollinPoetoehena/devhub-ansible-users.git
    scm: git
    version: 1.0.0
  - name: devhub.jumphost
    src: https://github.com/CollinPoetoehena/devhub-ansible-jumphost.git
    scm: git
    version: 1.0.0
  - name: devhub.mgmtvm
    src: https://github.com/CollinPoetoehena/devhub-ansible-mgmtvm.git
    scm: git
    version: 1.0.0
  - name: devhub.router
    src: https://github.com/CollinPoetoehena/devhub-ansible-router-custom.git
    scm: git
    version: 2.0.0
  - name: devhub.proxmox
    src: https://github.com/CollinPoetoehena/devhub-ansible-proxmox.git
    scm: git
    version: initial-setup # TODO: change to PRD version later when it is done and tested!
  - name: devhub.k8s
    src: https://github.com/CollinPoetoehena/devhub-ansible-k8s.git
    scm: git
    version: initial-setup # TODO: change to PRD version later when it is done and tested!
